INSERT INTO person(name, age, email) VALUES ('Tom', 25, 'tom@mail.com');
INSERT INTO person(name, age, email) VALUES ('Bob', 31, 'bob1@mail.com');
INSERT INTO person(name, age, email) VALUES ('Bob', 53, 'bob2@mail.com');
INSERT INTO person(name, age, email) VALUES ('Bob', 20, 'bob3@mail.com');
INSERT INTO person(name, age, email) VALUES ('Katy', 14, 'katy@mail.com');

SELECT * FROM person;
SELECT * FROM Item;

CREATE TABLE Item(
                     id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                     person_id int REFERENCES person(id) ON DELETE SET NULL,
                     item_name varchar(100) NOT NULL
);

INSERT INTO Item(person_id, item_name) VALUES (5, 'AirPods');
INSERT INTO Item(person_id, item_name) VALUES (5, 'PlayStation');
INSERT INTO Item(person_id, item_name) VALUES (5, 'TV');

